---
title: "Feature to Ontology"
author: "Sarah Scharfenberg"
date: "29 7 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description

## Input

## Output

## Files

```{r}
data_file <- system.file("extdata/Example_Coverage/example_smiles.csv", package = "MetClassNetR")
```

## Script

```{r, eval=FALSE}
## snipped is not executed in this vignette 

mztab <- MSnbase::MzTab(data_file)
  
sm <- MSnbase::smallMolecules(mztab)
# for the coverage it is irrelevant which ID the SMILES had before
data_tibble <- as_tibble(sm["smiles"])

## clean up empty SMILES
data_tibble <- data_tibble %>%
  filter(!is.na(smiles)) %>%
  distinct(smiles)
```


```{r}
data_tibble <- as_tibble(data.frame(smiles = read.csv(data_file,header=FALSE, 
                                                      stringsAsFactors = FALSE)[,1]))
```



Translate SMILES to InChIs and InChIKeys with RCDK.
```{r}
### rcdk InChIs from rinchi
 datainchis <- sapply(data_tibble$smiles,function(smi){
   if(!is.na(smi)){
     smim <- rcdk::parse.smiles(smi)
     if(!is.null(unlist(smim))){
       res <- rinchi::get.inchi(smi)
       return(res)
     }else{return(NA)}
   }else{return(NA)}
 })

 datainchiks <- data.frame(sapply(data_tibble$smiles,function(smi){
   #print(smi)
   if(!is.na(smi)){
     smim <- rcdk::parse.smiles(smi)
     if(!is.null(unlist(smim))){
       res <- rinchi::get.inchi.key(smi)
       return(res)
     }else{return(NA)}
   }else{return(NA)}
 }))

 data_tibble <- data_tibble %>%
   add_column(inchiFromRCDK=unlist(datainchis)) %>%
   add_column(inchikeyFromRCDK=as.character(unlist(datainchiks)))
```


## ChemOnt Class Annotation MTBLS1582


```{r, message=FALSE, eval=FALSE}
## snipped is not executed in this vignette 
## Time difference of 13.90753 hours

data_classes <- sapply(data_tibble$inchikeyFromRCDK,function(ik){
  #Sys.sleep(10)
  classific <- eval(classyfireR::get_classification(ik))
  if(!is.null(classific)){return(list(classific@classification))}   ## add list() to network processing
  return(NULL)
})

data_tibble <- data_tibble %>%
  add_column(classyfire_classes = data_classes)

tmp <- sapply(data_tibble$classyfire_classes,function(x){return(!is.null(unlist(x)))})
data_tibble <- data_tibble %>%
  mutate(classified = tmp)
rm(tmp)
```


```{r, message=FALSE, eval=TRUE}
load(system.file("extdata/Example_Coverage/data_tibble.Rdata", package = "MetClassNetR"))
```
