FROM sneumann/metclassnetr-base:latest

MAINTAINER Steffen Neumann <sneumann@ipb-halle.de>

LABEL Description="MetClassNet R environment."

ADD . /tmp/MetClassNetR
RUN R CMD INSTALL /tmp/MetClassNetR



